name: ZePipeline

on:
  push:
    branches: [ main ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-dependency-cache

      - name: Pull the release keystore
        env:
          KEYSTORE_URL: ${{ secrets.KEYSTORE_URL }}
        run: curl $KEYSTORE_URL -o keystore/zeapp-keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and test everything
        run: ./gradlew build

      - name: Sign the app with the new key
        env:
          KEYSTORE_FILE: ../keystore/zeapp-keystore
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
        run: ./gradlew clean assembleRelease

      - name: Upload binaries to a release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: ${{ format('Release T-{0}', github.run_id) }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/release/app-release.apk
          asset_name: ze-app-3.apk
          tag: ${{ github.run_id }}
          overwrite: true
